const product = [
    {
        _id: '125489695845',
        name: 'maïs blanc', 
        slug: 'maïs-blanc-785425',
        imageUrl: '/assets/products/mais-blanc.jpg',
        description: 'Le maïs blanc est une variété de maïs principalement cultivée pour sa couleur distinctive et ses qualités nutritionnelles. Contrairement au maïs jaune, le maïs blanc ne contient pas de caroténoïdes, ce qui lui donne sa couleur blanche. Il est riche en fibres, vitamines B, et contient des antioxydants bénéfiques pour la santé.',
        category: 'cereales',
        updated_at:'',
        created_at: '',  
    },
    {
        _id: '89559695845',
        name: 'maïs jaune', 
        slug: 'maïs-jaune-785485425',
        imageUrl: '/assets/products/mais-jaune.jpg',
        description: "Le maïs jaune est une céréale largement cultivée dans le monde entier pour ses grains nutritifs et polyvalents. Originaire d'Amérique centrale, il est une source importante de glucides et est riche en fibres, vitamines (notamment la vitamine A due à la présence de bêta-carotène), et minéraux. Utilisé à la fois pour la consommation humaine et animale, le maïs jaune se trouve dans une multitude de produits alimentaires tels que les tortillas, le popcorn, la farine de maïs, et les céréales pour petit-déjeuner.",
        category: 'cereales',
        updated_at:'',
        created_at: '',  
    },
    {
        _id: '8955968595845',
        name: 'maïs bleu', 
        slug: 'maïs-bleu-789585425',
        imageUrl: '/assets/products/mais-bleu.png',
        description: "Le maïs bleu, également connu sous le nom de maïs Hopi, est une variété ancienne de maïs cultivée principalement par les peuples indigènes des Amériques, notamment les Hopis du sud-ouest des États-Unis. Ce type de maïs est distinctif en raison de sa couleur bleue profonde, qui provient de pigments anthocyaniques, les mêmes que l'on trouve dans les myrtilles.",
        category: 'cereales',
        updated_at:'',
        created_at: '',  
    },
    {
        _id: '89559648795845',
        name: 'maïs rouge', 
        slug: 'maïs-rouge-789925125',
        imageUrl: '/assets/products/mais-bleu.png',
        description: "Le maïs rouge est une variété de maïs distincte par sa couleur rouge profonde, qui provient de pigments naturels appelés anthocyanines. Originaire des Amériques, cette variété est souvent cultivée pour des usages spécifiques, y compris la consommation humaine, la production de farine, et comme ingrédient dans diverses préparations culinaires traditionnelles et artisanales.",
        category: 'cereales',
        updated_at:'',
        created_at: '',  
    },
]