export const productDatas = [
    {
        _id: '125489695845',
        name: 'maïs blanc',
        slug: 'maïs-blanc-785425',
        imageUrl: '/assets/products/mais-blanc.jpg',
        description: "L'enjeu sur la production et la commercialisation du maïs est de taille aujourd'hui. Le maïs intervient fortement dans l'alimentation au niveau local ( Un gros marché à satisfaire). Il est également demandé par les usines locales et étrangères. Nous sommes présents sur toute la chaîne. Si vous souhaitez vous approvisionner.",
        category: 'cereales',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '89559695845',
        name: 'maïs jaune',
        slug: 'maïs-jaune-785485425',
        imageUrl: '/assets/products/mais-jaune.jpg',
        description: "Le maïs jaune est une céréale largement cultivée dans le monde entier pour ses grains nutritifs et polyvalents. Originaire d'Amérique centrale, il est une source importante de glucides et est riche en fibres, vitamines (notamment la vitamine A due à la présence de bêta-carotène), et minéraux. Utilisé à la fois pour la consommation humaine et animale, le maïs jaune se trouve dans une multitude de produits alimentaires tels que les tortillas, le popcorn, la farine de maïs, et les céréales pour petit-déjeuner.",
        category: 'cereales',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955968595845',
        name: 'maïs bleu',
        slug: 'maïs-bleu-789585425',
        imageUrl: '/assets/products/mais-bleu.png',
        description: "Le maïs bleu, également connu sous le nom de maïs Hopi, est une variété ancienne de maïs cultivée principalement par les peuples indigènes des Amériques, notamment les Hopis du sud-ouest des États-Unis. Ce type de maïs est distinctif en raison de sa couleur bleue profonde, qui provient de pigments anthocyaniques, les mêmes que l'on trouve dans les myrtilles.",
        category: 'cereales',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '89559648795845',
        name: 'maïs rouge',
        slug: 'maïs-rouge-789925125',
        imageUrl: '/assets/products/mais-rouge.png',
        description: "Le maïs rouge est une variété de maïs distincte par sa couleur rouge profonde, qui provient de pigments naturels appelés anthocyanines. Originaire des Amériques, cette variété est souvent cultivée pour des usages spécifiques, y compris la consommation humaine, la production de farine, et comme ingrédient dans diverses préparations culinaires traditionnelles et artisanales.",
        category: 'cereales',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh48795845',
        name: 'soja',
        slug: 'soja-789695125',
        imageUrl: '/assets/products/soja2.jpg',
        description: "La production de soja a pris de l'ampleur ces dernières années en Afrique. Très recherché sur le marché international, le Soja Africain fait l'objet de plusieurs spéculations. Nous avons un système complet qui nous permet de collecter, stocker, nettoyer, conditionner et livrer aux clients.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh4879jh785r45',
        name: 'cesame',
        slug: 'cesame-24964587125',
        imageUrl: '/assets/products/cesame.png',
        description: "Les graines de sésame interviennent dans les cuisines africaines, notamment au Togo, au Bénin, au Ghana, etc. Il constitue également une matière première pour des industries à l'international. Si vous êtes à la recherche du sésame, quelle que soit votre position géographique.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh487ui97sd85r45',
        name: 'Fonio',
        slug: 'fonio-24968897125',
        imageUrl: '/assets/products/fonio.png',
        description: "Le fonio regorge d'énormes qualités nutritionnelles, mais il peine à se développer à cause de plusieurs facteurs. Le grand défi est au niveau de sa transformation qui demeure pénible artisanalement. Nous nous positionnons pour promouvoir et valoriser la chaîne de production Fonio au Bénin et en Afrique de l’Ouest.",
        category: 'cereales',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh48df7ytpe97sd85r45',
        name: 'Karité',
        slug: 'karite-249695514477125',
        imageUrl: '/assets/products/karite.png',
        description: "Le karité constitue le troisième produit d'exportation du Bénin après le coton et l'anacarde et représente de ce fait une source non négligeable de devises. Dans la sous-région ouest-africaine, le Bénin figure au rang de quatrième producteur d'amandes de karité après le Mali, le Burkina Faso et le Nigeria avec un volume de production d'environ 30.000 tonnes de noix sèche.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh48dytf7ytpe97tsd85r45',
        name: 'Noix de Cajou',
        slug: 'noix-de-cajou-695544477125',
        imageUrl: '/assets/products/acadju.png',
        description: "Nous fournissons également les noix de Cajou, Deuxième produit d'exportation au Bénin.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh7448dytf7ytpe97tsd85r45',
        name: 'Arachides',
        slug: 'arachides-695787844477125',
        imageUrl: '/assets/products/arachide.png',
        description: "L'arachide est une plante cultivée principalement pour ses graines, qui sont consommées grillées ou transformées en beurre d'arachide. Elle appartient à la famille des Fabacées et est originaire d'Amérique du Sud. Cultivée dans de nombreuses régions tropicales et subtropicales, elle joue un rôle important dans l'alimentation humaine et animale ainsi que dans l'industrie agroalimentaire.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh57dytf7ytpe97tpsd85r45',
        name: 'Haricot',
        slug: 'haricot-77477125',
        imageUrl: '/assets/products/haricot.png',
        description: "Le haricot est une légumineuse au profil nutritionnel impressionnant, riche en protéines, en fibres et en divers nutriments essentiels. De sa forme allongée à sa texture tendre en passant par sa couleur variant du vert au jaune, chaque haricot révèle une délicatesse unique sous son enveloppe. Cultivé depuis des millénaires, ce légume polyvalent occupe une place de choix dans de nombreuses cuisines à travers le monde, offrant une palette de saveurs allant du sucré au terrien.",
        category: 'legumineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955gh7dytf97tpsd85r45',
        name: 'Graine de courge',
        slug: ' graine-de-courge-787455725',
        imageUrl: '/assets/products/graineCourge.png',
        description: "Les graines de courge, également connues sous le nom de pépins de courge, sont des graines comestibles récoltées à partir de différentes variétés de courges, notamment les courges d'hiver et les courges musquées. Elles sont considérées comme des graines oléagineuses, ce qui signifie qu'elles sont riches en huiles et en graisses bénéfiques pour la santé.",
        category: 'oleagineux',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955ghe97t4psd85r45',
        name: 'Ananas',
        slug: 'ananas-788757125',
        imageUrl: '/assets/products/ananas.png',
        description: "L'ananas est un fruit tropical originaire d'Amérique du Sud, largement cultivé dans les régions tropicales et subtropicales à travers le monde.",
        category: 'fruit',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955e97t445psd85r45',
        name: 'Mangue',
        slug: 'mangue-787125',
        imageUrl: '/assets/products/mange.png',
        description: "Le fruit de mangue, exotique et sucré, est une explosion de saveurs tropicales en bouche. Sa chair juteuse et parfumée, souvent d'un jaune orangé ou d'un rouge vif, évoque les chaudes journées ensoleillées des régions où il prospère. Délicieux à déguster frais ou en smoothie, ce fruit est également polyvalent en cuisine, ajoutant une touche de fraîcheur et de douceur à de nombreux plats sucrés et salés.",
        category: 'fruit',
        updated_at: '',
        created_at: '',
    },
    {
        _id: '8955e97t4psd85r45',
        name: 'Pastèque',
        slug: 'pasteque-787125',
        imageUrl: '/assets/products/pasteque.png',
        description: "La pastèque est un fruit juteux et rafraîchissant, caractérisé par sa chair rouge sucrée et ses graines noires. Avec sa peau verte striée, elle est une icône de l'été et est souvent dégustée en tranches lors des journées chaudes. Sa saveur douce et désaltérante en fait un favori lors des pique-niques et des barbecues, et elle est également appréciée dans les smoothies et les salades de fruits pour sa fraîcheur et son croquant.",
        category: 'fruit',
        updated_at: '',
        created_at: '',
    },





]