export const services = [
    [
        {
            _id: Math.random() * 15244,
            title: "BILLET D’AVION",
            image: "assets/images/services/1.jpg",
            content: "Des billets d’avions pour toutes les destinations au meilleur prix. Un grand choix de compagnies aériennes régulières et low cost pour tous vos déplacements.",
            created: new Date(),
        },
        // {
        //     _id: Math.random() * 15244,
        //     title: "TRAIN",
        //     image: "assets/images/services/2.jpg",
        //     content: "Pour vos déplacements en train, votre agence AFC TOURS peut effectuer toutes vos réservations. Les tarifs les plus adaptés vous seront proposés par votre conseiller voyages.",
        //     created: new Date(),
        // },
        {
            _id: Math.round((Math.random() * 15244 + 25)),
            title: "LOCATION DE VOITURE",
            image: "assets/images/services/3.jpg",
            content: "Nous avons pour vous le séjour qui vous convient le mieux. Des bords de la Méditerranée aux rivages de l’Océan Indien nous sommes en mesure de vous proposer les meilleurs séjours qualité prix.",
            created: new Date(),
        },
        {
            title: "SÉJOUR",
            image: "assets/images/services/4.jpg",
            content: "Nous avons pour vous le séjour qui vous convient le mieux. Des bords de la Méditerranée aux rivages de l’Océan Indien nous sommes en mesure de vous proposer les meilleurs séjours qualité prix.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "CIRCUIT",
            image: "assets/images/services/5.jpg",
            content: "Votre conseiller voyages AFC TOURS vous proposera des circuits accompagnés, des auto-tours, des safaris. Que vous ayez besoin d’être encadré ou d’aventure, le circuit de vos rêves est certainement chez nous.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "CROISIÈRE",
            image: "assets/images/services/6.jpg",
            content: "Les Fjords, la Méditerranée, les Caraïbes… les compagnies de croisières que nous distribuons pourront sans aucun doute vous proposer les escales que vous souhaitez découvrir.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "LOCATION",
            image: "assets/images/services/7.jpg",
            content: "Envie d’une villa ou d’une maison? Notre large offre d’hébergement vous permettra de trouver partout dans le monde la location pour vos futures vacances.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "COURT SEJOUR / WEEK-END",
            image: "assets/images/services/8.jpg",
            content: "Les capitales européennes sont certainement des villes idéales pour des escapades culturelles ou pour aller faire la fête le temps d’un week-end. Découvrez nos courts séjours.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOL+HÔTEL",
            image: "assets/images/services/9.jpg",
            content: "Vous souhaitez que votre voyage s’adapte à vous et non le contraire ? Nous pourrons vous proposer le vol et l’hôtel qui vous conviennent le mieux. Construisez vous-même votre voyage !",
            created: new Date(),
        }
    ],
    /****  */
    [
        {
            _id: Math.random() * 15244,
            title: "PROMO",
            image: "assets/images/services/10.jpg",
            content: "Que ce soit des premières minutes ou des offres de dernières minutes, nos fournisseurs nous communiquent des tarifs promotionnels tout au long de l’année. Contactez-nous pour découvrir les offres du moment.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "ÉVÉNEMENTIEL",
            image: "assets/images/services/11.jpg",
            content: "AFC TOURS est aussi en mesure d’assurer l’organisation de vos événements familiaux et professionnels. N’hésitez pas à nous consulter.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOYAGE D’AFFAIRES",
            image: "assets/images/services/12.jpg",
            content: "Pour vos déplacements professionnels, AFC TOURS saura vous trouver les billets les plus adaptés à votre type de transport ainsi que les hôtels les mieux situés et proposant les services dont vous aurez besoin.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOYAGE EN GROUPE",
            image: "assets/images/services/13.jpg",
            content: "Donnez-nous le nombre de participants, votre destination et le type de services voulus. Nous vous proposerons une offre de qualité au prix le plus bas.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "BILLETTERIE SPECTACLE",
            image: "assets/images/services/14.jpg",
            content: "La dernière pièce de théâtre, un événement sportif, une exposition… AFC TOURS peut également vous faire profiter de sa billetterie spectacle.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "DEMARCHES VISAS",
            image: "assets/images/services/15.jpg",
            content: "AFC Tours vous accompagne dans vos démarches d'obtension de visas.",
            created: new Date(),
        },
        
        {
            _id: Math.random() * 15244,
            title: "ASSURANCES",
            image: "assets/images/services/16.jpg",
            content: "Afin de vous savoir le mieux couvert possible, nous négocions régulièrement pour vous les assurances les plus adaptées. N’hésitez pas à nous contacter pour connaître nos différentes formules.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "SERVICES SPÉCIAUX",
            image: "assets/images/services/17.jpg",
            content: "AFC TOURS propose des divers services spécifiques : VIP, Personnes âgées, Personnes porteurs d’un handicap, mineurs voyageant seuls, etc.",
            created: new Date(),
        },
    ],
    [
        {
            _id: Math.random() * 15244,
            title: "TOUT COMPRIS",
            image: "assets/images/services/18.jpg",
            content: "Pour ne pas se poser de questions d’argent pendant ses vacances, retrouvez notre sélection de clubs et d’hôtels proposant une formule Tout-Inclus.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOYAGE DE LUXE",
            image: "assets/images/services/19.jpg",
            content: "Les plus belles adresses sur les plus belle plages du monde. Raffinement, élégance et personnalisation sont les maitres-mots de notre sélection de voyages.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOYAGE DE NOCES",
            image: "assets/images/services/20.jpg",
            content: "Parce que votre voyage de noces doit être unique : retrouvez-vous en toute intimité avec votre moitié pour immortaliser votre union dans un cadre idyllique.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "DERNIÈRES MINUTES",
            image: "assets/images/services/21.jpg",
            content: "Besoins de changer d’air, envie de faire sa valise pour demain ? Profitez de nos bons plans en Dernières Minutes pour partir au plus près comme au bout du monde.",
            created: new Date(),
        },
        {
            _id: Math.random() * 15244,
            title: "VOYAGE EN FAMILLE",
            image: "assets/images/services/22.jpg",
            content: "Trouvez votre séjour idéal parmi nos milliers d'offres disponibles partout dans le monde !",
            created: new Date(),
        },
        
    ],
]